heroin:
  material: END_CRYSTAL
  display-name: "&cHeroin"
  lore:
    - "&7A high-risk, high-reward combat enhancer."
    - "&7Not recommended for daily use."
  effects:
    STRENGTH:
      duration: 600
      amplifier: 1
    SPEED:
      duration: 2400
      amplifier: 1

henbane:
  material: RABBIT_FOOT
  display-name: "&4Henbane"
  lore:
    - "&7An ancient herb of the wild."
    - "&7Fuels blind fury."
  effects:
    STRENGTH:
      duration: 600
      amplifier: 2
    SPEED:
      duration: 300
      amplifier: 2
    BLINDNESS:
      duration: 300
      amplifier: 0
