name: DrugsV2
version: '1.0'
main: com.drugs.DrugsV2
api-version: '1.21'

commands:
  drugs:
    description: Opens the drug selection GUI or gives a drug to a player.
    usage: /drugs [give <player> <drugId> [amount]]
    permission: drugs.menu

permissions:
  drugs.menu:
    description: Allows access to the drug menu
    default: true

  drugs.give:
    description: Allows giving drugs to players via /drugs give
    default: op
