name: DrugsV2
version: '1.1'
main: com.drugs.DrugsV2
api-version: '1.21'

commands:
  drugs:
    description: Opens the drug selection GUI or runs admin commands
    usage: /drugs [give/help/purge/reload/list]
    permission: drugs.menu

  tolerance:
    description: View your current drug tolerance levels
    usage: /tolerance
    permission: drugs.tolerance

permissions:
  drugs.menu:
    description: Allows access to the drug menu
    default: true

  drugs.give:
    description: Allows giving drugs to players via /drugs give
    default: op

  drugs.tolerance:
    description: Allows using /tolerance
    default: true

  drugs.admin.reload:
    description: Allows reloading all configs
    default: op

  drugs.admin.purge:
    description: Allows purging a player’s tolerance
    default: op

  drugs.admin.list:
    description: Allows viewing the registered drug list
    default: op
